version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"  # Port pour accéder à SonarQube via http://localhost:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar  # URL de connexion à PostgreSQL
      - SONARQUBE_JDBC_USERNAME=admin  # Nom d'utilisateur PostgreSQL
      - SONARQUBE_JDBC_PASSWORD=23jdiAB1234  # Mot de passe PostgreSQL
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Désactive les vérifications de démarrage Elasticsearch
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db  # Assure que SonarQube démarre après PostgreSQL

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=sonar  # Nom de la base de données
      - POSTGRES_USER=admin  # Nom d'utilisateur PostgreSQL
      - POSTGRES_PASSWORD=23jdiAB1234  # Mot de passe PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistance des données PostgreSQL
    networks:
      - sonarnet

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data:

networks:
  sonarnet:
    driver: bridge
