version: '3.8'

services:
  backend:
    build:
      context: C:/Users/ADMIN/Desktop/Projet_fac/ApplicationGLA_SurveillanceCrypto
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: crypto-backend
    networks:
      - crypto-network

  frontend:
    build:
      context: C:/Users/ADMIN/Desktop/Projet_fac/ApplicationGLA_SurveillanceCrypto/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: crypto-frontend
    depends_on:
      - backend
    networks:
      - crypto-network
    environment:
      - REACT_APP_API_URL=http://localhost:8082

networks:
  crypto-network:
    driver: bridge