version: '3.8'

services:
  backend:
    build:
      context: C:/Users/ADMIN/Desktop/Projet_fac/ApplicationGLA_SurveillanceCrypto # Chemin absolu vers le répertoire backend
    container_name: backend
    ports:
      - "8082:8080"  # Le backend sera accessible sur http://localhost:8082
    networks:
      - app-network

  frontend:
    build:
      context: C:/Users/ADMIN/Desktop/Projet_fac/ApplicationGLA_SurveillanceCrypto/frontend # Chemin absolu vers le répertoire frontend
    container_name: frontend
    ports:
      - "80:80"  # Le frontend sera accessible sur http://localhost
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080  # L'URL du backend à utiliser dans le frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
