name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Spring Boot Application
        run: |
          cd src/main
          ./mvnw clean install

      - name: Build Docker image for Backend
        run: |
          docker build -t my-backend-image .

      - name: Push Docker image (if using DockerHub)
        run: |
          docker tag my-backend-image <DOCKER_USERNAME>/my-backend-image:latest
          docker push <DOCKER_USERNAME>/my-backend-image:latest

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React application
        run: |
          cd frontend
          npm run build

      - name: Build Docker image for Frontend
        run: |
          cd frontend
          docker build -t my-frontend-image .

      - name: Push Docker image (if using DockerHub)
        run: |
          docker tag my-frontend-image <DOCKER_USERNAME>/my-frontend-image:latest
          docker push <DOCKER_USERNAME>/my-frontend-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to your environment (example)
        run: |
          echo "Deploy your application here"
          # Ajoutez ici vos commandes de déploiement, comme une connexion à un serveur ou un cloud (par exemple, AWS, GCP, etc.)

  locust-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Locust
        run: |
          pip install locust

      - name: Run Locust tests
        run: |
          locust -f locustfile.py --host=http://localhost:8080  # Modifiez l'URL pour votre serveur backend
